name = "FlexSketch"
uuid = "a2ed2604-9bde-4bf4-bb6a-228c4e3bfee9"
authors = ["Tomev <rybotycki.tomasz+github@gmail.com>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
